<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PluginsSeeder extends Seeder
{
    // Category constants
    private const CATEGORY_SALES = 'sales';
    private const CATEGORY_MARKETING = 'marketing';
    private const CATEGORY_COMMUNICATION = 'communication';
    private const CATEGORY_ANALYTICS = 'analytics';
    private const CATEGORY_AI = 'ai';
    private const CATEGORY_DOCUMENTS = 'documents';
    private const CATEGORY_SERVICE = 'service';
    private const CATEGORY_ADMIN = 'admin';

    // Tier constants
    private const TIER_CORE = 'core';
    private const TIER_PROFESSIONAL = 'professional';
    private const TIER_ADVANCED = 'advanced';
    private const TIER_ENTERPRISE = 'enterprise';

    // Pricing model constants
    private const PRICING_INCLUDED = 'included';
    private const PRICING_PER_USER = 'per_user';
    private const PRICING_FLAT = 'flat';
    private const PRICING_USAGE = 'usage';

    public function run(): void
    {
        // Clear existing data
        DB::table('plugin_bundles')->truncate();
        DB::table('plugins')->truncate();

        $now = now();

        // ============================================
        // TIER 1: CORE PLUGINS (Included in all plans)
        // ============================================
        $corePlugins = [
            [
                'slug' => 'core-modules',
                'name' => 'Modules & Records',
                'description' => 'Core module management and record CRUD operations',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_CORE,
                'pricing_model' => self::PRICING_INCLUDED,
                'icon' => 'database',
                'features' => json_encode(['Custom modules', 'Record management', 'Field customization', 'Relationships']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 1,
            ],
            [
                'slug' => 'core-datatable',
                'name' => 'DataTable Views',
                'description' => 'Advanced data table with sorting, filtering, and inline editing',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_CORE,
                'pricing_model' => self::PRICING_INCLUDED,
                'icon' => 'table',
                'features' => json_encode(['Sortable columns', 'Advanced filters', 'Inline editing', 'Column customization']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 2,
            ],
            [
                'slug' => 'core-kanban',
                'name' => 'Kanban Views',
                'description' => 'Visual pipeline management with drag-and-drop',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_CORE,
                'pricing_model' => self::PRICING_INCLUDED,
                'icon' => 'layout-kanban',
                'features' => json_encode(['Drag-and-drop', 'Pipeline stages', 'Card customization', 'Quick actions']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 3,
            ],
            [
                'slug' => 'core-dashboards',
                'name' => 'Dashboards',
                'description' => 'Customizable dashboards with widgets',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_CORE,
                'pricing_model' => self::PRICING_INCLUDED,
                'icon' => 'layout-dashboard',
                'features' => json_encode(['Widget library', 'Custom layouts', 'Real-time data', 'Sharing']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 4,
            ],
            [
                'slug' => 'core-workflows-basic',
                'name' => 'Basic Workflows',
                'description' => 'Automation workflows with basic triggers and actions',
                'category' => self::CATEGORY_ADMIN,
                'tier' => self::TIER_CORE,
                'pricing_model' => self::PRICING_INCLUDED,
                'icon' => 'workflow',
                'features' => json_encode(['Trigger on create/update', 'Email actions', 'Field updates', 'Up to 5 workflows']),
                'requirements' => null,
                'limits' => json_encode(['workflows' => 5]),
                'display_order' => 5,
            ],
            [
                'slug' => 'core-reports',
                'name' => 'Basic Reports',
                'description' => 'Standard reporting and analytics',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_CORE,
                'pricing_model' => self::PRICING_INCLUDED,
                'icon' => 'bar-chart-2',
                'features' => json_encode(['Pre-built reports', 'Basic charts', 'Export to CSV', 'Date filtering']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 6,
            ],
            [
                'slug' => 'core-email',
                'name' => 'Email Integration',
                'description' => 'Gmail and Outlook email sync',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_CORE,
                'pricing_model' => self::PRICING_INCLUDED,
                'icon' => 'mail',
                'features' => json_encode(['Email sync', 'Email tracking', 'Templates', 'Scheduling']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 7,
            ],
            [
                'slug' => 'core-import-export',
                'name' => 'Import/Export',
                'description' => 'Data import and export capabilities',
                'category' => self::CATEGORY_ADMIN,
                'tier' => self::TIER_CORE,
                'pricing_model' => self::PRICING_INCLUDED,
                'icon' => 'download',
                'features' => json_encode(['CSV import', 'Excel export', 'Field mapping', 'Duplicate handling']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 8,
            ],
        ];

        // ============================================
        // TIER 2: PROFESSIONAL ADD-ONS
        // ============================================
        $professionalPlugins = [
            [
                'slug' => 'forecasting-pro',
                'name' => 'Sales Forecasting',
                'description' => 'Advanced sales forecasting with AI-powered predictions',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 15.00,
                'price_yearly' => 144.00,
                'icon' => 'trending-up',
                'features' => json_encode(['Pipeline forecasting', 'Historical trends', 'Accuracy tracking', 'Team rollups', 'Adjustments']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 10,
            ],
            [
                'slug' => 'quotes-invoices',
                'name' => 'Quotes & Invoices',
                'description' => 'Professional quote and invoice management',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 20.00,
                'price_yearly' => 192.00,
                'icon' => 'file-text',
                'features' => json_encode(['Quote builder', 'Invoice generation', 'PDF export', 'Payment tracking', 'Templates']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 11,
            ],
            [
                'slug' => 'meeting-scheduler',
                'name' => 'Meeting Scheduler',
                'description' => 'Calendly-style meeting booking with calendar sync',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 10.00,
                'price_yearly' => 96.00,
                'icon' => 'calendar',
                'features' => json_encode(['Booking pages', 'Calendar sync', 'Meeting types', 'Reminders', 'Custom availability']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 12,
            ],
            [
                'slug' => 'duplicate-detection',
                'name' => 'Duplicate Detection',
                'description' => 'AI-powered duplicate record detection and merging',
                'category' => self::CATEGORY_ADMIN,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 10.00,
                'price_yearly' => 96.00,
                'icon' => 'copy',
                'features' => json_encode(['Fuzzy matching', 'Bulk merge', 'Custom rules', 'Merge history', 'Real-time alerts']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 13,
            ],
            [
                'slug' => 'deal-rotting',
                'name' => 'Deal Rotting Alerts',
                'description' => 'Automatic alerts for stale deals in pipeline',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 8.00,
                'price_yearly' => 76.00,
                'icon' => 'alert-triangle',
                'features' => json_encode(['Stage-based thresholds', 'Email digests', 'Dashboard widget', 'Custom rules']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 14,
            ],
            [
                'slug' => 'web-forms-pro',
                'name' => 'Public Web Forms',
                'description' => 'Embeddable lead capture forms',
                'category' => self::CATEGORY_MARKETING,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 15.00,
                'price_yearly' => 144.00,
                'icon' => 'file-input',
                'features' => json_encode(['Drag-drop builder', 'Custom styling', 'Embed codes', 'Analytics', 'Spam protection']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 15,
            ],
            [
                'slug' => 'workflows-advanced',
                'name' => 'Advanced Workflows',
                'description' => 'Unlimited workflows with advanced conditions',
                'category' => self::CATEGORY_ADMIN,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 15.00,
                'price_yearly' => 144.00,
                'icon' => 'git-branch',
                'features' => json_encode(['Unlimited workflows', 'Conditional branching', 'Scheduled triggers', 'Webhooks', 'Custom actions']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 16,
            ],
            [
                'slug' => 'blueprints-pro',
                'name' => 'Advanced Blueprints',
                'description' => 'Process blueprints with SLAs and approvals',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 12.00,
                'price_yearly' => 115.00,
                'icon' => 'map',
                'features' => json_encode(['Unlimited blueprints', 'SLA enforcement', 'Approval flows', 'Requirements', 'Compliance tracking']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 17,
            ],
            [
                'slug' => 'custom-reports',
                'name' => 'Custom Reports',
                'description' => 'Advanced report builder with custom formulas',
                'category' => self::CATEGORY_ANALYTICS,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 10.00,
                'price_yearly' => 96.00,
                'icon' => 'pie-chart',
                'features' => json_encode(['Report builder', 'Custom formulas', 'Scheduled reports', 'Multiple formats', 'Sharing']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 18,
            ],
        ];

        // ============================================
        // TIER 3: ADVANCED ADD-ONS (Differentiators)
        // ============================================
        $advancedPlugins = [
            [
                'slug' => 'time-machine',
                'name' => 'Time Machine',
                'description' => 'View any record at any point in time with full history',
                'category' => self::CATEGORY_ADMIN,
                'tier' => self::TIER_ADVANCED,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 20.00,
                'price_yearly' => 192.00,
                'icon' => 'clock',
                'features' => json_encode(['Point-in-time view', 'Field change history', 'Diff comparison', 'Restore capability', 'Audit trail']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 20,
            ],
            [
                'slug' => 'scenario-planner',
                'name' => 'Scenario Planner',
                'description' => 'What-if analysis and scenario modeling for deals',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_ADVANCED,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 25.00,
                'price_yearly' => 240.00,
                'icon' => 'git-compare',
                'features' => json_encode(['Scenario creation', 'Deal adjustments', 'Comparison view', 'Gap analysis', 'Commit tracking']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 21,
            ],
            [
                'slug' => 'revenue-graph',
                'name' => 'Revenue Intelligence Graph',
                'description' => 'Visual relationship mapping for revenue opportunities',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_ADVANCED,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 30.00,
                'price_yearly' => 288.00,
                'icon' => 'share-2',
                'features' => json_encode(['Relationship visualization', 'Path analysis', 'Influence mapping', 'Revenue attribution', 'Interactive graph']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 22,
            ],
            [
                'slug' => 'deal-rooms',
                'name' => 'Deal Rooms',
                'description' => 'Collaborative spaces for buyer-seller engagement',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_ADVANCED,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 25.00,
                'price_yearly' => 240.00,
                'icon' => 'users',
                'features' => json_encode(['Branded rooms', 'Document sharing', 'Action items', 'Chat', 'Engagement analytics']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 23,
            ],
            [
                'slug' => 'competitor-battlecards',
                'name' => 'Competitor Battlecards',
                'description' => 'Competitive intelligence and objection handling',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_ADVANCED,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 20.00,
                'price_yearly' => 192.00,
                'icon' => 'swords',
                'features' => json_encode(['Battlecard builder', 'Objection library', 'Win/loss tracking', 'Team feedback', 'Analytics']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 24,
            ],
            [
                'slug' => 'process-recorder',
                'name' => 'Process Recorder',
                'description' => 'Record actions and generate workflows automatically',
                'category' => self::CATEGORY_ADMIN,
                'tier' => self::TIER_ADVANCED,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 15.00,
                'price_yearly' => 144.00,
                'icon' => 'video',
                'features' => json_encode(['Action recording', 'Step parameterization', 'Workflow generation', 'Template library']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 25,
            ],
        ];

        // ============================================
        // COMMUNICATION CHANNELS (Flat pricing)
        // ============================================
        $communicationPlugins = [
            [
                'slug' => 'live-chat',
                'name' => 'Live Chat Widget',
                'description' => 'Embeddable chat widget for websites',
                'category' => self::CATEGORY_SERVICE,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_FLAT,
                'price_monthly' => 25.00,
                'price_yearly' => 240.00,
                'icon' => 'message-circle',
                'features' => json_encode(['Customizable widget', 'Agent routing', 'Canned responses', 'File sharing', 'Visitor tracking']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 30,
            ],
            [
                'slug' => 'whatsapp-integration',
                'name' => 'WhatsApp Business',
                'description' => 'WhatsApp Business API integration',
                'category' => self::CATEGORY_COMMUNICATION,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_FLAT,
                'price_monthly' => 30.00,
                'price_yearly' => 288.00,
                'icon' => 'message-square',
                'features' => json_encode(['Template messages', 'Rich media', 'Automated replies', 'Contact sync', 'Analytics']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 31,
            ],
            [
                'slug' => 'sms-automation',
                'name' => 'SMS Automation',
                'description' => 'SMS messaging with Twilio integration',
                'category' => self::CATEGORY_COMMUNICATION,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_FLAT,
                'price_monthly' => 20.00,
                'price_yearly' => 192.00,
                'icon' => 'smartphone',
                'features' => json_encode(['SMS campaigns', 'Two-way messaging', 'Templates', 'Opt-out management', 'Delivery tracking']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 32,
            ],
            [
                'slug' => 'team-chat',
                'name' => 'Team Chat Integration',
                'description' => 'Slack and Microsoft Teams integration',
                'category' => self::CATEGORY_COMMUNICATION,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_FLAT,
                'price_monthly' => 15.00,
                'price_yearly' => 144.00,
                'icon' => 'hash',
                'features' => json_encode(['Deal notifications', 'Channel posting', 'Slash commands', 'User mapping']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 33,
            ],
            [
                'slug' => 'shared-inbox',
                'name' => 'Shared Team Inbox',
                'description' => 'Collaborative email inbox for teams',
                'category' => self::CATEGORY_SERVICE,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_FLAT,
                'price_monthly' => 25.00,
                'price_yearly' => 240.00,
                'icon' => 'inbox',
                'features' => json_encode(['Shared inbox', 'Assignment rules', 'Collision detection', 'Internal notes', 'SLAs']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 34,
            ],
        ];

        // ============================================
        // MARKETING SUITE
        // ============================================
        $marketingPlugins = [
            [
                'slug' => 'marketing-campaigns',
                'name' => 'Marketing Campaigns',
                'description' => 'Multi-channel marketing campaign management',
                'category' => self::CATEGORY_MARKETING,
                'tier' => self::TIER_ADVANCED,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 35.00,
                'price_yearly' => 336.00,
                'icon' => 'megaphone',
                'features' => json_encode(['Campaign builder', 'Email marketing', 'A/B testing', 'Analytics', 'Audience segmentation']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 40,
            ],
            [
                'slug' => 'smart-cadences',
                'name' => 'Smart Cadences',
                'description' => 'Multi-touch sales sequences with optimization',
                'category' => self::CATEGORY_MARKETING,
                'tier' => self::TIER_ADVANCED,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 30.00,
                'price_yearly' => 288.00,
                'icon' => 'repeat',
                'features' => json_encode(['Sequence builder', 'Multi-channel', 'AI optimization', 'Performance tracking', 'Templates']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 41,
            ],
        ];

        // ============================================
        // THIRD-PARTY INTEGRATIONS
        // ============================================
        $integrationPlugins = [
            [
                'slug' => 'integration-quickbooks',
                'name' => 'QuickBooks Online',
                'description' => 'Sync invoices, contacts, and payments with QuickBooks',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 15.00,
                'price_yearly' => 144.00,
                'icon' => 'calculator',
                'features' => json_encode(['Contact sync', 'Invoice sync', 'Payment tracking', 'Bi-directional']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 60,
            ],
            [
                'slug' => 'integration-xero',
                'name' => 'Xero',
                'description' => 'Sync invoices, contacts, and payments with Xero',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 15.00,
                'price_yearly' => 144.00,
                'icon' => 'file-spreadsheet',
                'features' => json_encode(['Contact sync', 'Invoice sync', 'Payment tracking', 'Bi-directional']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 61,
            ],
            [
                'slug' => 'integration-stripe',
                'name' => 'Stripe',
                'description' => 'Process payments and manage subscriptions via Stripe',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_FLAT,
                'price_monthly' => 25.00,
                'price_yearly' => 240.00,
                'icon' => 'credit-card',
                'features' => json_encode(['Payment processing', 'Subscription billing', 'Customer sync', 'Webhooks']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 62,
            ],
            [
                'slug' => 'integration-docusign',
                'name' => 'DocuSign',
                'description' => 'Send documents for electronic signature via DocuSign',
                'category' => self::CATEGORY_DOCUMENTS,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 20.00,
                'price_yearly' => 192.00,
                'icon' => 'file-signature',
                'features' => json_encode(['Send for signature', 'Template library', 'Status tracking', 'Signed document storage']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 64,
            ],
            [
                'slug' => 'integration-calendly',
                'name' => 'Calendly',
                'description' => 'Auto-create contacts when meetings are booked',
                'category' => self::CATEGORY_SALES,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_FLAT,
                'price_monthly' => 10.00,
                'price_yearly' => 96.00,
                'icon' => 'calendar-check',
                'features' => json_encode(['Meeting webhooks', 'Contact creation', 'Activity logging', 'Task creation']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 66,
            ],
            [
                'slug' => 'integration-slack',
                'name' => 'Slack',
                'description' => 'Get CRM notifications in Slack channels',
                'category' => self::CATEGORY_COMMUNICATION,
                'tier' => self::TIER_CORE,
                'pricing_model' => self::PRICING_INCLUDED,
                'icon' => 'hash',
                'features' => json_encode(['Deal notifications', 'Task alerts', 'Channel posting', 'Slash commands']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 67,
            ],
            [
                'slug' => 'integration-zoom',
                'name' => 'Zoom',
                'description' => 'Schedule and track Zoom meetings',
                'category' => self::CATEGORY_COMMUNICATION,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_FLAT,
                'price_monthly' => 15.00,
                'price_yearly' => 144.00,
                'icon' => 'video',
                'features' => json_encode(['Create meetings', 'Sync participants', 'Recording links', 'Activity logging']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 68,
            ],
            [
                'slug' => 'integration-mailchimp',
                'name' => 'Mailchimp',
                'description' => 'Sync contacts and campaigns with Mailchimp',
                'category' => self::CATEGORY_MARKETING,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_FLAT,
                'price_monthly' => 15.00,
                'price_yearly' => 144.00,
                'icon' => 'mail',
                'features' => json_encode(['Contact sync', 'Campaign tracking', 'List management', 'Engagement data']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 69,
            ],
            [
                'slug' => 'integration-google-drive',
                'name' => 'Google Drive',
                'description' => 'Attach and access files from Google Drive',
                'category' => self::CATEGORY_DOCUMENTS,
                'tier' => self::TIER_PROFESSIONAL,
                'pricing_model' => self::PRICING_FLAT,
                'price_monthly' => 10.00,
                'price_yearly' => 96.00,
                'icon' => 'hard-drive',
                'features' => json_encode(['File attachments', 'Folder browsing', 'Document preview', 'Quick upload']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 70,
            ],
        ];

        // ============================================
        // AI/ML FEATURES
        // ============================================
        $aiPlugins = [
            [
                'slug' => 'ai-email-composition',
                'name' => 'AI Email Composition',
                'description' => 'AI-powered email writing assistance',
                'category' => self::CATEGORY_AI,
                'tier' => self::TIER_ENTERPRISE,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 30.00,
                'price_yearly' => 288.00,
                'icon' => 'sparkles',
                'features' => json_encode(['Email generation', 'Tone adjustment', 'Subject lines', 'Personalization', 'Templates']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 50,
            ],
            [
                'slug' => 'ai-lead-scoring',
                'name' => 'AI Lead Scoring',
                'description' => 'Machine learning-based lead prioritization',
                'category' => self::CATEGORY_AI,
                'tier' => self::TIER_ENTERPRISE,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 40.00,
                'price_yearly' => 384.00,
                'icon' => 'brain',
                'features' => json_encode(['Predictive scoring', 'Custom models', 'Score explanations', 'Auto-assignment', 'Trends']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 51,
            ],
            [
                'slug' => 'ai-meeting-summarization',
                'name' => 'Meeting Summarization',
                'description' => 'AI-powered meeting notes and action items',
                'category' => self::CATEGORY_AI,
                'tier' => self::TIER_ENTERPRISE,
                'pricing_model' => self::PRICING_PER_USER,
                'price_monthly' => 35.00,
                'price_yearly' => 336.00,
                'icon' => 'file-audio',
                'features' => json_encode(['Transcription', 'Summary generation', 'Action extraction', 'CRM sync', 'Search']),
                'requirements' => null,
                'limits' => null,
                'display_order' => 52,
            ],
        ];

        // Insert all plugins
        $allPlugins = array_merge(
            $corePlugins,
            $professionalPlugins,
            $advancedPlugins,
            $communicationPlugins,
            $marketingPlugins,
            $integrationPlugins,
            $aiPlugins
        );

        foreach ($allPlugins as $pluginData) {
            $pluginData['is_active'] = true;
            $pluginData['created_at'] = $now;
            $pluginData['updated_at'] = $now;
            $pluginData['price_monthly'] = $pluginData['price_monthly'] ?? null;
            $pluginData['price_yearly'] = $pluginData['price_yearly'] ?? null;

            DB::table('plugins')->insert($pluginData);
        }

        // ============================================
        // BUNDLES
        // ============================================
        $bundles = [
            [
                'slug' => 'sales-pro-pack',
                'name' => 'Sales Pro Pack',
                'description' => 'Essential sales tools for growing teams',
                'plugins' => json_encode(['forecasting-pro', 'quotes-invoices', 'meeting-scheduler', 'deal-rotting']),
                'price_monthly' => 40.00,
                'price_yearly' => 384.00,
                'discount_percent' => 25,
                'icon' => 'briefcase',
                'display_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'revenue-intelligence-pack',
                'name' => 'Revenue Intelligence Pack',
                'description' => 'Advanced insights for enterprise sales',
                'plugins' => json_encode(['time-machine', 'scenario-planner', 'revenue-graph', 'competitor-battlecards']),
                'price_monthly' => 75.00,
                'price_yearly' => 720.00,
                'discount_percent' => 21,
                'icon' => 'line-chart',
                'display_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'omnichannel-pack',
                'name' => 'Omnichannel Pack',
                'description' => 'Connect with customers on every channel',
                'plugins' => json_encode(['live-chat', 'whatsapp-integration', 'sms-automation', 'shared-inbox']),
                'price_monthly' => 80.00,
                'price_yearly' => 768.00,
                'discount_percent' => 20,
                'icon' => 'radio',
                'display_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'marketing-hub',
                'name' => 'Marketing Hub',
                'description' => 'Complete marketing automation suite',
                'plugins' => json_encode(['marketing-campaigns', 'smart-cadences', 'web-forms-pro']),
                'price_monthly' => 70.00,
                'price_yearly' => 672.00,
                'discount_percent' => 17,
                'icon' => 'target',
                'display_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'ai-copilot',
                'name' => 'AI Copilot',
                'description' => 'AI-powered sales assistance',
                'plugins' => json_encode(['ai-email-composition', 'ai-lead-scoring', 'ai-meeting-summarization']),
                'price_monthly' => 85.00,
                'price_yearly' => 816.00,
                'discount_percent' => 24,
                'icon' => 'bot',
                'display_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        foreach ($bundles as $bundleData) {
            DB::table('plugin_bundles')->insert($bundleData);
        }
    }
}
